baseURL = "https://yangxt65535.github.io/"
title = "yangxt65535"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
preserveTaxonomyNames = true
enableRobotsTXT = true

[languages]
  [languages.zh-cn]
    locale = "zh-CN"
    label = "中文"
    weight = 1
    title = "yangxt65535"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS"]

[module]
  [[module.imports]]
    path = "github.com/zhaohuabing/hugo-theme-cleanwhite"

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "yangxt65535 的博客"
  description = "技术笔记与学习记录"
  keyword = "yangxt65535, blog, Hugo, 技术笔记"
  slogan = "施工中。。。"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "这里什么也没有"
  omit_categories = false

  page_view_counter = false
  algolia_search = false

  sidebar_about_description = "Ciallo～(∠·ω< )⌒☆"
  sidebar_avatar = "" 

  featured_tags = true
  featured_condition_size = 0

  reward = false
  friends = false
  bookmarks = false
  about_me = true
  last_posts = true

  artalk_enable = false

  [params.social]
    rss = true
    github = "https://github.com/yangxt65535"

  [[params.additional_menus]]
    title = "ARCHIVE"
    href = "/archive/"
  [[params.additional_menus]]
    title = "PROJECTS"
    href = "/projects/"
  [[params.additional_menus]]
    title = "ABOUT"
    href = "/about/"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
